/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Win10
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form EmpresaFrame
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        MenuArquivoNovo = new javax.swing.JMenuItem();
        MenuArquivoSalvar = new javax.swing.JMenuItem();
        MenuArquivoFechar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuArquivoSair = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        MenuEmpresa = new javax.swing.JMenu();
        MenuEmpresaCriar = new javax.swing.JMenuItem();
        MenuEmpresaEditar = new javax.swing.JMenuItem();
        MenuSetor = new javax.swing.JMenu();
        MenuSetorCriar = new javax.swing.JMenuItem();
        MenuSetorEditar = new javax.swing.JMenuItem();
        MenuColaborador = new javax.swing.JMenu();
        MenuColaboradorNovo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuArquivo.setText("Arquivo");

        MenuArquivoNovo.setText("Novo");
        MenuArquivo.add(MenuArquivoNovo);

        MenuArquivoSalvar.setText("Salvar");
        MenuArquivo.add(MenuArquivoSalvar);

        MenuArquivoFechar.setText("Fechar");
        MenuArquivo.add(MenuArquivoFechar);
        MenuArquivo.add(jSeparator1);

        MenuArquivoSair.setText("Sair");
        MenuArquivo.add(MenuArquivoSair);

        jMenuBar1.add(MenuArquivo);

        MenuEditar.setText("Editar");
        jMenuBar1.add(MenuEditar);

        MenuEmpresa.setText("Empresa");

        MenuEmpresaCriar.setText("Criar");
        MenuEmpresaCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpresaCriarActionPerformed(evt);
            }
        });
        MenuEmpresa.add(MenuEmpresaCriar);

        MenuEmpresaEditar.setText("Editar");
        MenuEmpresaEditar.setEnabled(false);
        MenuEmpresa.add(MenuEmpresaEditar);

        jMenuBar1.add(MenuEmpresa);

        MenuSetor.setText("Setor");

        MenuSetorCriar.setText("Criar");
        MenuSetor.add(MenuSetorCriar);

        MenuSetorEditar.setText("Editar");
        MenuSetor.add(MenuSetorEditar);

        jMenuBar1.add(MenuSetor);

        MenuColaborador.setText("Colaborador");

        MenuColaboradorNovo.setText("Novo");
        MenuColaborador.add(MenuColaboradorNovo);

        jMenuBar1.add(MenuColaborador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuEmpresaCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpresaCriarActionPerformed
        // TODO add your handling code here:
        
        new DialogEmpresa().setVisible;
        novo.setVisible(true);
    }//GEN-LAST:event_MenuEmpresaCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenuItem MenuArquivoFechar;
    private javax.swing.JMenuItem MenuArquivoNovo;
    private javax.swing.JMenuItem MenuArquivoSair;
    private javax.swing.JMenuItem MenuArquivoSalvar;
    private javax.swing.JMenu MenuColaborador;
    private javax.swing.JMenuItem MenuColaboradorNovo;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenu MenuEmpresa;
    private javax.swing.JMenuItem MenuEmpresaCriar;
    private javax.swing.JMenuItem MenuEmpresaEditar;
    private javax.swing.JMenu MenuSetor;
    private javax.swing.JMenuItem MenuSetorCriar;
    private javax.swing.JMenuItem MenuSetorEditar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
